#!/usr/bin/env python3
"""Turn the raw Overpass pull into restaurants.js used by the map.

REAL fields (OpenStreetMap): name, category, cuisine, street, lat, lng.
PLACEHOLDER fields (until you actually prospect): status (all 'new'),
fitScore + monthlyValue (rough estimates so the heat modes demo), opening (mock).
Deterministic: same input -> same output, so the map is stable across reloads.
"""
import json, hashlib, re
from fit import score_fit

RAW = "overpass_raw.json"
OUT = "restaurants.js"

# Note: amenity=fast_food is intentionally excluded — we don't service fast food.
CAT = {
    "restaurant": "Restaurant",
    "cafe": "Cafe",
    "bar": "Bar",
    "pub": "Bar",
}

def det(seed_str, salt=""):
    """Deterministic 0..1 from a string."""
    h = hashlib.md5((salt + seed_str).encode()).hexdigest()
    return int(h[:8], 16) / 0xFFFFFFFF

def titlecase_cuisine(c):
    if not c:
        return ""
    return ", ".join(w.replace("_", " ").strip().title() for w in c.split(";")[:2])

data = json.load(open(RAW))["elements"]
out = []
chains_dropped = 0
for el in data:
    tags = el.get("tags", {})
    name = tags.get("name")
    if not name:
        continue  # skip unnamed nodes — not useful prospects
    if tags.get("shop") == "bakery":
        category = "Bakery"
    elif tags.get("amenity") == "fast_food":
        continue  # not a market we service
    else:
        category = CAT.get(tags.get("amenity"), "Restaurant")

    sid = str(el["id"])
    cuisine = titlecase_cuisine(tags.get("cuisine", ""))

    # Real Chefs' Warehouse fit score; drop commodity chains entirely.
    fit_score, chain = score_fit(name, category, tags.get("cuisine", ""))
    if chain:
        chains_dropped += 1
        continue

    out.append({
        "id": el["id"],
        "name": name,
        "category": category,
        "cuisine": cuisine,
        "street": tags.get("addr:street", ""),
        "hours": tags.get("opening_hours", ""),            # OSM opening_hours (may be "")
        "lat": round(el["lat"], 6),
        "lng": round(el["lon"], 6),
        "fitScore": fit_score,                             # real CW fit heuristic
        "monthlyValue": int(det(sid, "val") ** 2 * 2800),  # $ potential estimate
        "status": "new",                                   # nothing prospected yet
        "opening": None,
    })

# NOTE: New openings are NOT flagged here anymore — they come from the real
# NY SLA feed via openings_feed.py -> openings.js. These 773 are existing venues.
out.sort(key=lambda p: p["id"])

cats = {}
for p in out:
    cats[p["category"]] = cats.get(p["category"], 0) + 1

with open(OUT, "w") as f:
    f.write("// Auto-generated by build_data.py — real Westchester venues from OpenStreetMap.\n")
    f.write("// Real: name, category, cuisine, street, lat, lng. Placeholder: fitScore, monthlyValue, status, opening.\n")
    f.write("window.REAL_RESTAURANTS = ")
    json.dump(out, f, ensure_ascii=False)
    f.write(";\n")

print(f"wrote {len(out)} venues -> {OUT}  (dropped {chains_dropped} chains)")
print("by category:", cats)
