// Auto-generated from "CT-Westchester Prospecting List.xlsx" (2026-08-31) — 96 hand-researched,
// verified-open prospects across Westchester NY + Fairfield CT, with evidence-based fit ratings
// (menus, press, ownership, multi-unit groups — see the spreadsheet's "Why it fits" column).
//
// Merged into PROSPECTS by index.html at load:
//   osmId set   -> overrides that OSM venue's fitScore and attaches contact/why data
//                  (keeps the OSM id, so any tracker status/notes on it survive)
//   osmId null  -> appended as a new venue (OSM was missing it — common for hotel
//                  restaurants, bakeries, caterers)
// fitScore here = myRating (1-5, human) mapped 5->96 4->85 3->70 2->55 onto the
// fit.py 0-100 scale. approxLoc: true = town-centroid fallback, pin is not exact.
// Optional file: the map works unchanged without it.
window.CURATED_PROSPECTS = [
 {
  "id": "cur-001",
  "name": "Kanopi",
  "category": "Restaurant",
  "cuisine": "Portuguese farm-to-table",
  "street": "1 Renaissance Sq, 42nd Fl (The Opus), White Plains, NY 10601",
  "town": "White Plains",
  "state": "NY",
  "lat": 41.032398,
  "lng": -73.76777,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 761-4242",
  "contact": "Chef Anthony Gonçalves · info@kanopitherestaurant.com · kanopitherestaurant.com",
  "segment": "Fine dining / hotel",
  "whyFit": "Chef-driven tasting menu atop the Opus hotel + large banquet/event arm (Kanopi Events). Premium buyer across every category.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-002",
  "name": "Mulino's of Westchester",
  "category": "Restaurant",
  "cuisine": "Northern Italian",
  "street": "99 Court St, White Plains, NY 10601",
  "town": "White Plains",
  "state": "NY",
  "lat": 41.029993,
  "lng": -73.766844,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 761-1818",
  "contact": "mulinosny.com",
  "segment": "Fine dining",
  "whyFit": "White-tablecloth institution; scratch Italian kitchen (imported oil, seafood, veal) + heavy private-party volume.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-003",
  "name": "Benjamin Steakhouse Westchester",
  "category": "Restaurant",
  "cuisine": "Dry-aged steakhouse",
  "street": "610 Hartsdale Rd, White Plains, NY 10607",
  "town": "White Plains",
  "state": "NY",
  "lat": 41.037908,
  "lng": -73.810758,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 428-6868",
  "contact": "benjaminsteakhouse.com/westchester",
  "segment": "Fine dining",
  "whyFit": "USDA Prime dry-aged program — direct Allen Brothers pitch. Part of NY-based Benjamin Restaurant Group (multi-unit).",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-004",
  "name": "Dubrovnik Restaurant",
  "category": "Restaurant",
  "cuisine": "Croatian / Adriatic seafood",
  "street": "721 Main St, New Rochelle, NY 10801",
  "town": "New Rochelle",
  "state": "NY",
  "lat": 40.90359,
  "lng": -73.78899,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 637-3777",
  "contact": "Owner Zeljko 'Jerry' Tomic · dubrovniknyevents@gmail.com · dubrovnikny.com",
  "segment": "Fine dining",
  "whyFit": "Michelin Guide-listed; whole fish + octopus menu — premium seafood (FAO 34 octopus story) and olive oil. Also private events.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 8600440407
 },
 {
  "id": "cur-005",
  "name": "One Pier Steakhouse",
  "category": "Restaurant",
  "cuisine": "Steakhouse / seafood",
  "street": "1 Van Der Donck St, Yonkers, NY 10701",
  "town": "Yonkers",
  "state": "NY",
  "lat": 40.935904,
  "lng": -73.902887,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 457-0175",
  "contact": "onepiersteakhouse.com",
  "segment": "Fine dining",
  "whyFit": "New upscale steakhouse on the Yonkers waterfront (ex-Dolphin space). New openings = best moment to win the house account.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-006",
  "name": "Lulu Cake Boutique",
  "category": "Bakery",
  "cuisine": "High-end custom cakes",
  "street": "40 Garth Rd, Scarsdale, NY 10583",
  "town": "Scarsdale",
  "state": "NY",
  "lat": 40.987877,
  "lng": -73.80993,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 722-8300",
  "contact": "Owner Jay Muse · everythinglulu.com",
  "segment": "Bakery-patisserie",
  "whyFit": "Top-of-market wedding cake studio — couverture chocolate (Valrhona/Chicoa), butter, specialty flour. Pastry is CW's sweet spot.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-007",
  "name": "Lusardi's of Larchmont",
  "category": "Restaurant",
  "cuisine": "Northern Italian",
  "street": "1885 Palmer Ave, Larchmont, NY 10538",
  "town": "Larchmont",
  "state": "NY",
  "lat": 40.933654,
  "lng": -73.758393,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 834-5555",
  "contact": "Owner Mauro Lusardi",
  "segment": "Fine dining",
  "whyFit": "Two-unit family group (sibling on the UES). Veal, game, fresh pasta — proven premium-ingredient buyer.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 7530414405
 },
 {
  "id": "cur-008",
  "name": "Patisserie Salzburg",
  "category": "Bakery",
  "cuisine": "Austrian patisserie",
  "street": "2 Second St, Rye, NY 10580",
  "town": "Rye",
  "state": "NY",
  "lat": 40.984616,
  "lng": -73.683603,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 921-4458",
  "contact": "patisseriesalzburg.com",
  "segment": "Bakery-patisserie",
  "whyFit": "Butter-intensive Viennese pastry; 3 units (Rye/Stamford/New Canaan) — one buyer, three doors.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-009",
  "name": "L'inizio",
  "category": "Restaurant",
  "cuisine": "Italian / New American",
  "street": "698 Saw Mill River Rd, Ardsley, NY 10502",
  "town": "Ardsley",
  "state": "NY",
  "lat": 41.017769,
  "lng": -73.844419,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 693-5400",
  "contact": "Chef-owners Scott & Heather Fratangelo · liniziony.com",
  "segment": "Fine dining",
  "whyFit": "Michelin Guide-listed husband/wife chef team; pastry chef on premises — buys savory AND pastry lines. Plus catering.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-010",
  "name": "Goosefeather",
  "category": "Restaurant",
  "cuisine": "Cantonese / Asian",
  "street": "49 E Sunnyside Ln (Tarrytown House Estate), Tarrytown, NY 10591",
  "town": "Tarrytown",
  "state": "NY",
  "lat": 41.050966,
  "lng": -73.857929,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 829-5454",
  "contact": "Chef-owner Dale Talde · info@goosefeatherny.com",
  "segment": "Fine dining / hotel",
  "whyFit": "Michelin Guide-listed, celebrity-chef-driven, inside a hotel estate — protein/seafood-forward premium menu.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 10117337366
 },
 {
  "id": "cur-011",
  "name": "Hudson Farmer & the Fish",
  "category": "Restaurant",
  "cuisine": "Seafood / farm-to-table",
  "street": "11 River St, Sleepy Hollow, NY 10591",
  "town": "Sleepy Hollow",
  "state": "NY",
  "lat": 41.080543,
  "lng": -73.867418,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 631-8380",
  "contact": "Chef Michael Kaphan & Edward Taylor · farmerandthefish.com",
  "segment": "Fine dining",
  "whyFit": "Raw bar + open kitchen; small multi-unit group (Purdys farm restaurant + NYC) — one relationship, several accounts.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-012",
  "name": "Crabtree's Kittle House",
  "category": "Restaurant",
  "cuisine": "Contemporary American",
  "street": "11 Kittle Rd, Chappaqua, NY 10514",
  "town": "Chappaqua",
  "state": "NY",
  "lat": 41.181525,
  "lng": -73.74531,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 666-8044",
  "contact": "Owner John Crabtree · kittlehouse.com",
  "segment": "Fine dining",
  "whyFit": "Landmark inn, newly renovated, legendary wine cellar, big private-event business — classic premium fine-dining account.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-013",
  "name": "Moderne Barn",
  "category": "Restaurant",
  "cuisine": "New American",
  "street": "430 Bedford Rd, Armonk, NY 10504",
  "town": "Armonk",
  "state": "NY",
  "lat": 41.126509,
  "lng": -73.693006,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 730-0001",
  "contact": "Livanos family (Livanos Restaurant Group) · modernebarn.com",
  "segment": "Fine dining",
  "whyFit": "High-volume flagship of the Livanos group (Oceana NYC, City Limits) — big-ticket account with group-wide potential.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-014",
  "name": "La Tulipe Desserts",
  "category": "Bakery",
  "cuisine": "European fine patisserie",
  "street": "455 Lexington Ave, Mount Kisco, NY 10549",
  "town": "Mount Kisco",
  "state": "NY",
  "lat": 41.192573,
  "lng": -73.732774,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 242-4555",
  "contact": "Master pastry chef Maarten Steenman · latulipedesserts.com",
  "segment": "Bakery-patisserie",
  "whyFit": "One of Westchester's most acclaimed classical patisseries — exactly the couverture/high-fat-butter customer CW wants.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-015",
  "name": "The Tavern at Bedford Post Inn",
  "category": "Restaurant",
  "cuisine": "Seasonal American",
  "street": "954 Old Post Rd, Bedford, NY 10506",
  "town": "Bedford",
  "state": "NY",
  "lat": 41.219249,
  "lng": -73.624903,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 234-7800",
  "contact": "inn@bedfordpostinn.com · bedfordpostinn.com",
  "segment": "Fine dining / hotel",
  "whyFit": "Relais & Châteaux inn — restaurant + inn breakfast + events. Premium price point and hotel F&B volume.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-016",
  "name": "Jean-Jacques' Culinary Creations",
  "category": "Bakery",
  "cuisine": "French bakery / catering",
  "street": "468 Bedford Rd, Pleasantville, NY 10570",
  "town": "Pleasantville",
  "state": "NY",
  "lat": 41.133174,
  "lng": -73.792746,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(914) 747-8191",
  "contact": "Owner Jens Gabrillargues · info@jean-jacques.com",
  "segment": "Bakery + caterer",
  "whyFit": "30+ yr French pastry house + full-service caterer with exclusive venues — dual-segment butter/chocolate/flour volume.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-017",
  "name": "The Cottage — Greenwich",
  "category": "Restaurant",
  "cuisine": "New American / Japanese",
  "street": "49 Greenwich Ave, Greenwich, CT 06830",
  "town": "Greenwich",
  "state": "CT",
  "lat": 41.030268,
  "lng": -73.626699,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 769-1220",
  "contact": "Chef-owner Brian Lewis · thecottage.kitchen/greenwich",
  "segment": "Fine dining",
  "whyFit": "One of Fairfield County's most acclaimed chef-driven kitchens; Lewis group (Cottage Westport, OKO) is multi-unit and premium-sourcing throughout.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-018",
  "name": "Rebeccas",
  "category": "Restaurant",
  "cuisine": "Modern American / French",
  "street": "265 Glenville Rd, Greenwich, CT 06831",
  "town": "Greenwich",
  "state": "CT",
  "lat": 41.038123,
  "lng": -73.664073,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 532-9270",
  "contact": "Owners Rebecca Kirhoffer & Reza Khorshidi · rebeccasgreenwich.com",
  "segment": "Fine dining",
  "whyFit": "Chef-owned institution (20+ yrs), open glass kitchen; foie gras/truffle/Dover sole menu — classic luxury-ingredient buyer.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-019",
  "name": "L'Escale (Delamar Greenwich Harbor)",
  "category": "Restaurant",
  "cuisine": "French / Provençal",
  "street": "500 Steamboat Rd, Greenwich, CT 06830",
  "town": "Greenwich",
  "state": "CT",
  "lat": 41.018101,
  "lng": -73.623373,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 661-4600",
  "contact": "Exec Chef Frederic Kieffer · lescalerestaurant.com",
  "segment": "Fine dining / hotel",
  "whyFit": "Waterfront hotel flagship, breakfast-through-dinner + banquets — heavy butter, olive oil, seafood. Two minutes from your front door.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-020",
  "name": "Mediterraneo of Greenwich",
  "category": "Restaurant",
  "cuisine": "Mediterranean seafood",
  "street": "366 Greenwich Ave, Greenwich, CT 06830",
  "town": "Greenwich",
  "state": "CT",
  "lat": 41.0262,
  "lng": -73.6282,
  "approxLoc": true,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 629-4747",
  "contact": "zhospitalitygroup.com",
  "segment": "Upscale casual",
  "whyFit": "Anchor of Z Hospitality Group (Terra Greenwich, Solé New Canaan, Aurora Rye) — one relationship opens a 4-unit NY/CT group.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-021",
  "name": "Valbella",
  "category": "Restaurant",
  "cuisine": "Northern Italian",
  "street": "1309 E Putnam Ave, Riverside, CT 06878",
  "town": "Riverside",
  "state": "CT",
  "lat": 41.043012,
  "lng": -73.57562,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 637-1155",
  "contact": "Owner David Ghatanfard · valbellagreenwich.com",
  "segment": "Fine dining",
  "whyFit": "High-check special-occasion Italian, famed wine cellar + private dining — prime veal/beef, seafood, imported Italian goods.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 8277007975
 },
 {
  "id": "cur-022",
  "name": "Aux Délices Foods by Debra Ponzek",
  "category": "Caterer",
  "cuisine": "French-American",
  "street": "1075 E Putnam Ave, Riverside, CT 06878",
  "town": "Riverside",
  "state": "CT",
  "lat": 41.040948,
  "lng": -73.585724,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 698-1066",
  "contact": "Chef-owner Debra Ponzek (ex-Montrachet NYC) · auxdelicesfoods.com",
  "segment": "Caterer / gourmet market",
  "whyFit": "Four locations (Riverside, Greenwich, Darien, Westport), scratch bakery + corporate/social catering — high-volume multi-unit account.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-023",
  "name": "Marcia Selden Catering & Events",
  "category": "Caterer",
  "cuisine": "Luxury event catering",
  "street": "65 Research Dr, Stamford, CT 06906",
  "town": "Stamford",
  "state": "CT",
  "lat": 41.076924,
  "lng": -73.519404,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 353-8000",
  "contact": "Robin Selden (exec chef) & Jeffrey Selden · info@marciaselden.com",
  "segment": "Caterer",
  "whyFit": "One of the Northeast's top luxury caterers (events 10–1,000 guests) — big, consistent volume across proteins, dairy, pastry.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-024",
  "name": "Restaurant L'Ostal",
  "category": "Restaurant",
  "cuisine": "Provençal French",
  "street": "22 Center St, Darien, CT 06820",
  "town": "Darien",
  "state": "CT",
  "lat": 41.076623,
  "lng": -73.469299,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(475) 328-9629",
  "contact": "Chef-owner Jared Sippel (Michelin-kitchen pedigree) · restaurantlostal.com",
  "segment": "Fine dining",
  "whyFit": "Destination chef-owned Provençal room — top-tier French product: olive oil, butter, seafood.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-025",
  "name": "Elm Restaurant",
  "category": "Restaurant",
  "cuisine": "New American",
  "street": "73 Elm St, New Canaan, CT 06840",
  "town": "New Canaan",
  "state": "CT",
  "lat": 41.146902,
  "lng": -73.493717,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 920-4994",
  "contact": "Exec Chef/Partner Luke Venner · elmrestaurant.com",
  "segment": "Fine dining",
  "whyFit": "New Canaan's flagship chef-driven room — dry-aged beef, day-boat seafood; textbook specialty account.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-026",
  "name": "Match Restaurant",
  "category": "Restaurant",
  "cuisine": "New American",
  "street": "98 Washington St, South Norwalk, CT 06854",
  "town": "Norwalk (SoNo)",
  "state": "CT",
  "lat": 41.098935,
  "lng": -73.418089,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 852-1088",
  "contact": "Chef-owner Matt Storch · mstorch@matchsono.com",
  "segment": "Fine dining",
  "whyFit": "SoNo's flagship chef-driven kitchen 25+ yrs; wood-fired oven, scratch pasta, raw bar; second unit in Westport.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-027",
  "name": "SoNo Baking Company & Café",
  "category": "Bakery",
  "cuisine": "Artisan bread / pastry",
  "street": "101 Water St, South Norwalk, CT 06854",
  "town": "Norwalk (SoNo)",
  "state": "CT",
  "lat": 41.096453,
  "lng": -73.415843,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 847-7666",
  "contact": "Founder John Barricelli · sonobaking.com",
  "segment": "Bakery-patisserie",
  "whyFit": "High-volume artisan bakery with an active WHOLESALE program supplying county restaurants — serious butter/flour/chocolate volume.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-028",
  "name": "The Cottage — Westport",
  "category": "Restaurant",
  "cuisine": "New American / Japanese",
  "street": "256 Post Rd E, Westport, CT 06880",
  "town": "Westport",
  "state": "CT",
  "lat": 41.141096,
  "lng": -73.356779,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 557-3701",
  "contact": "Chef-owner Brian Lewis · thecottage.kitchen",
  "segment": "Fine dining",
  "whyFit": "Lewis group flagship — ingredient-obsessed tasting-style menu; pitch the group (Greenwich + OKO) as one relationship.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-029",
  "name": "OKO Westport",
  "category": "Restaurant",
  "cuisine": "Japanese sushi / robata",
  "street": "6 Wilton Rd, Westport, CT 06880",
  "town": "Westport",
  "state": "CT",
  "lat": 41.144017,
  "lng": -73.365277,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 557-8404",
  "contact": "Chef-owner Brian Lewis · okokitchen.com",
  "segment": "Fine dining",
  "whyFit": "Premium sushi/robata — high-end seafood, wagyu, specialty imports; second OKO in Rye, NY.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-030",
  "name": "Artisan (Delamar Southport)",
  "category": "Restaurant",
  "cuisine": "Farm-to-table French-American",
  "street": "275 Old Post Rd, Southport, CT 06890",
  "town": "Southport",
  "state": "CT",
  "lat": 41.138196,
  "lng": -73.287013,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 307-4222",
  "contact": "Exec Chef/Partner Frederic Kieffer · artisansouthport.com",
  "segment": "Fine dining / hotel",
  "whyFit": "Delamar hotel flagship + banquets; same chef-partner as L'Escale (Greenwich Hospitality Group) — a multi-property pitch.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-031",
  "name": "Isabelle et Vincent",
  "category": "Bakery",
  "cuisine": "French patisserie",
  "street": "1903 Post Rd, Fairfield, CT 06824",
  "town": "Fairfield",
  "state": "CT",
  "lat": 41.140933,
  "lng": -73.265141,
  "approxLoc": null,
  "fitScore": 96,
  "myRating": 5,
  "phone": "(203) 292-8022",
  "contact": "Isabelle & Vincent Koenig (French master pastry chef) · isabelleetvincentbakery.com",
  "segment": "Bakery-patisserie",
  "whyFit": "True French patisserie — croissants, entremets, chocolates all in-house; ideal premium butter/chocolate/flour account.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-032",
  "name": "Spadaro Roman Kitchen",
  "category": "Restaurant",
  "cuisine": "Roman Italian",
  "street": "211 E Main St, New Rochelle, NY 10801",
  "town": "New Rochelle",
  "state": "NY",
  "lat": 40.915099,
  "lng": -73.771612,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 235-4595",
  "contact": "Spadaro family · spadaroromankitchen@gmail.com",
  "segment": "Fine dining",
  "whyFit": "Chef-driven, famous for handmade pasta — heavy 00 flour, olive oil, butter, cheese usage.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-033",
  "name": "La Fontanella",
  "category": "Restaurant",
  "cuisine": "Northern Italian",
  "street": "115 Wolfs Ln, Pelham, NY 10803",
  "town": "Pelham",
  "state": "NY",
  "lat": 40.907023,
  "lng": -73.811341,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 738-3008",
  "contact": "lafontanellany.com",
  "segment": "Fine dining",
  "whyFit": "White-tablecloth special-occasion room; veal/seafood-heavy menu.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-034",
  "name": "Underhills Crossing",
  "category": "Restaurant",
  "cuisine": "New American / French",
  "street": "74.5 Pondfield Rd, Bronxville, NY 10708",
  "town": "Bronxville",
  "state": "NY",
  "lat": 40.941725,
  "lng": -73.834782,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 337-1200",
  "contact": "underhillscrossing.com",
  "segment": "Upscale casual",
  "whyFit": "Executive-chef-led seasonal kitchen with private events — fits specialty produce, seafood, dairy.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 8805937479
 },
 {
  "id": "cur-035",
  "name": "Burrata Wood Fired Pizza",
  "category": "Restaurant",
  "cuisine": "Neapolitan pizza / pasta",
  "street": "425 White Plains Rd, Eastchester, NY 10709",
  "town": "Eastchester",
  "state": "NY",
  "lat": 40.956344,
  "lng": -73.813674,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 337-3700",
  "contact": "burratapizza.com",
  "segment": "Upscale pizzeria",
  "whyFit": "Michelin Guide-listed; already committed to imported 00 flour, olive oil, premium dairy. High-volume unit.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-036",
  "name": "Martine's Fine Bake Shoppe",
  "category": "Bakery",
  "cuisine": "European bakery / café",
  "street": "10 Fisher Ave, Tuckahoe, NY 10707",
  "town": "Tuckahoe",
  "state": "NY",
  "lat": 40.958559,
  "lng": -73.820018,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 346-8650",
  "contact": "martinesfinebakeshoppe.com",
  "segment": "Bakery-patisserie",
  "whyFit": "Two units (Tuckahoe + Scarsdale) — core butter/flour/chocolate volume across both.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 12228535720
 },
 {
  "id": "cur-037",
  "name": "Moscato Ristorante",
  "category": "Restaurant",
  "cuisine": "Italian",
  "street": "874 Scarsdale Ave, Scarsdale, NY 10583",
  "town": "Scarsdale",
  "state": "NY",
  "lat": 40.986281,
  "lng": -73.808866,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 723-5700",
  "contact": "Instagram @moscato_restaurant",
  "segment": "Fine dining",
  "whyFit": "Upscale white-tablecloth Italian with big private-party trade — premium proteins + imported Italian goods.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-038",
  "name": "Le Provençal Bistro",
  "category": "Restaurant",
  "cuisine": "Provençal French",
  "street": "436 Mamaroneck Ave, Mamaroneck, NY 10543",
  "town": "Mamaroneck",
  "state": "NY",
  "lat": 40.952146,
  "lng": -73.736425,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 777-2324",
  "contact": "info@provencalbistro.com · leprovencalbistro.com",
  "segment": "Fine dining",
  "whyFit": "One of the few true French rooms in the territory — real butter, cream, and olive oil volume.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 7840397480
 },
 {
  "id": "cur-039",
  "name": "Ruby's Oyster Bar & Bistro",
  "category": "Restaurant",
  "cuisine": "Seafood / French bistro",
  "street": "45 Purchase St, Rye, NY 10580",
  "town": "Rye",
  "state": "NY",
  "lat": 40.997287,
  "lng": -73.692398,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 921-4166",
  "contact": "rubysoysterbar.com (Pearl Restaurant Group)",
  "segment": "Upscale casual",
  "whyFit": "Raw bar + daily fish program; anchor of local multi-unit Pearl Restaurant Group — cross-sell to sister spots.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-040",
  "name": "Frankie & Johnnie's Steakhouse",
  "category": "Restaurant",
  "cuisine": "Steakhouse",
  "street": "77 Purchase St, Rye, NY 10580",
  "town": "Rye",
  "state": "NY",
  "lat": 40.998001,
  "lng": -73.692597,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 925-3900",
  "contact": "frankieandjohnnies.com",
  "segment": "Fine dining",
  "whyFit": "Family-owned since 1926 (NYC + Rye only). Prime beef, shrimp, oysters — core CW categories.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-041",
  "name": "The Kneaded Bread",
  "category": "Bakery",
  "cuisine": "Artisan bread",
  "street": "181 N Main St, Port Chester, NY 10573",
  "town": "Port Chester",
  "state": "NY",
  "lat": 41.004444,
  "lng": -73.660012,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 937-9489",
  "contact": "Owner-baker Jeff Kohn · thekneadedbread.com",
  "segment": "Bakery",
  "whyFit": "Hand-made artisan bakery since 1998; heavy flour/butter user and wholesales bread to area restaurants.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-042",
  "name": "Trattoria Vivolo",
  "category": "Restaurant",
  "cuisine": "Regional Italian",
  "street": "301 Halstead Ave, Harrison, NY 10528",
  "town": "Harrison",
  "state": "NY",
  "lat": 40.969,
  "lng": -73.7126,
  "approxLoc": true,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 835-6199",
  "contact": "Chef-owner Dean Vivolo · trattoriavivolo.com",
  "segment": "Upscale casual",
  "whyFit": "Hands-on chef-owner (ex-NYC); house-made pastas, seasonal regional menus — classic scratch kitchen.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-043",
  "name": "The Parlor",
  "category": "Restaurant",
  "cuisine": "Wood-fired Neapolitan",
  "street": "14 Cedar St, Dobbs Ferry, NY 10522",
  "town": "Dobbs Ferry",
  "state": "NY",
  "lat": 41.015271,
  "lng": -73.870884,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 478-8200",
  "contact": "Chef-owner David DiBari · Meagan@EatSeriousHaveFun.com",
  "segment": "Chef-driven casual",
  "whyFit": "NYT 'Excellent'; high-profile chef with small local group — 00 flour, imported cheese, whole-animal butchery.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-044",
  "name": "Half Moon",
  "category": "Restaurant",
  "cuisine": "New American / raw bar",
  "street": "1 High St, Dobbs Ferry, NY 10522",
  "town": "Dobbs Ferry",
  "state": "NY",
  "lat": 41.012047,
  "lng": -73.878467,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 693-4130",
  "contact": "halfmoonhudson.com",
  "segment": "Upscale casual",
  "whyFit": "High-volume riverfront destination + events; same group as Harvest on Hudson (Hastings) — multi-unit.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-045",
  "name": "Boro6 Wine Bar",
  "category": "Restaurant",
  "cuisine": "Mediterranean enoteca",
  "street": "549 Warburton Ave, Hastings-on-Hudson, NY 10706",
  "town": "Hastings-on-Hudson",
  "state": "NY",
  "lat": 40.995179,
  "lng": -73.882324,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 231-9200",
  "contact": "Paul Molakides & Jennifer Lynn Aaronson · boro6winebar.com",
  "segment": "Upscale casual",
  "whyFit": "Michelin Guide-listed; house-cured fish, cheese/charcuterie, in-house baking — ideal for specialty cheese + olive oil.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-046",
  "name": "Antoinette's Patisserie",
  "category": "Bakery",
  "cuisine": "French pastry / café",
  "street": "417 Warburton Ave, Hastings-on-Hudson, NY 10706",
  "town": "Hastings-on-Hudson",
  "state": "NY",
  "lat": 40.990603,
  "lng": -73.883395,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 478-7200",
  "contact": "—",
  "segment": "Bakery-patisserie",
  "whyFit": "Daily scratch French pastry, open 7 days — steady butter, chocolate, flour buyer.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-047",
  "name": "Red Hat on the River",
  "category": "Restaurant",
  "cuisine": "French-American bistro",
  "street": "1 Bridge St, Irvington, NY 10533",
  "town": "Irvington",
  "state": "NY",
  "lat": 41.041011,
  "lng": -73.873177,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 568-3233",
  "contact": "redhatontheriver.com",
  "segment": "Upscale casual",
  "whyFit": "Destination riverfront bistro with oyster bar + large private-event business — seafood, butter, pastry volume.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 12827581478
 },
 {
  "id": "cur-048",
  "name": "Le Jardin du Roi",
  "category": "Restaurant",
  "cuisine": "French bistro",
  "street": "95 King St, Chappaqua, NY 10514",
  "town": "Chappaqua",
  "state": "NY",
  "lat": 41.159217,
  "lng": -73.771877,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 238-1368",
  "contact": "lejardinchappaqua.com",
  "segment": "Upscale casual",
  "whyFit": "All-day French café/bistro since 2001 + private catering — French butter, quality flour, bistro proteins.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-049",
  "name": "Zero Otto Nove",
  "category": "Restaurant",
  "cuisine": "Salerno Italian",
  "street": "55 Old Route 22, Armonk, NY 10504",
  "town": "Armonk",
  "state": "NY",
  "lat": 41.119318,
  "lng": -73.718137,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 273-0089",
  "contact": "Chef-owner Roberto Paciullo · zeroottonove.com/armonk",
  "segment": "Upscale casual",
  "whyFit": "Arthur Avenue Paciullo group, 4 locations — olive oil, 00 flour, imported specialty; multi-unit upside.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-050",
  "name": "Village Social Kitchen & Bar",
  "category": "Restaurant",
  "cuisine": "Seasonal New American",
  "street": "251 E Main St, Mount Kisco, NY 10549",
  "town": "Mount Kisco",
  "state": "NY",
  "lat": 41.20166,
  "lng": -73.725854,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 864-1255",
  "contact": "Founder Joe Bueti · Exec Chef Mogan Anthony · villagesocialkb.com",
  "segment": "Upscale casual",
  "whyFit": "Chef ex-Jean-Georges/Nobu; second location in Rye + catering arm — small local group.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-051",
  "name": "140 Kitchen",
  "category": "Restaurant",
  "cuisine": "Asian-Southern American",
  "street": "911 South St, Peekskill, NY 10566",
  "town": "Peekskill",
  "state": "NY",
  "lat": 41.2901,
  "lng": -73.9204,
  "approxLoc": true,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 257-4000",
  "contact": "Co-owner Enzo De Raco · Exec Chef Shauna Leigh Franz",
  "segment": "Upscale casual",
  "whyFit": "Newly opened (2025-26) by the 140 Grand team — new openings are the best moment to win the house account.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-052",
  "name": "Peter Pratt's Inn",
  "category": "Restaurant",
  "cuisine": "American",
  "street": "673 Croton Heights Rd, Yorktown Heights, NY 10598",
  "town": "Yorktown Heights",
  "state": "NY",
  "lat": 41.247069,
  "lng": -73.784871,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(914) 962-4090",
  "contact": "Pelinku family (owners since 2022) · peterprattsinn.com",
  "segment": "Fine dining",
  "whyFit": "Destination farmhouse fine dining + events; new ownership may be open to new supplier relationships.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-053",
  "name": "Polpo Restaurant & Saloon",
  "category": "Restaurant",
  "cuisine": "Italian",
  "street": "554 Old Post Rd #3, Greenwich, CT 06830",
  "town": "Greenwich",
  "state": "CT",
  "lat": 41.020122,
  "lng": -73.643956,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 629-1999",
  "contact": "polporestaurantgreenwich.com",
  "segment": "Fine dining",
  "whyFit": "White-tablecloth Italian for the expense-account crowd; prime steaks, imported product, house pastas.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-054",
  "name": "Le Fat Poodle",
  "category": "Restaurant",
  "cuisine": "French bistro",
  "street": "20 Arcadia Rd, Old Greenwich, CT 06870",
  "town": "Old Greenwich",
  "state": "CT",
  "lat": 41.032273,
  "lng": -73.566454,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 717-1515",
  "contact": "lefatpoodle.com",
  "segment": "Upscale casual",
  "whyFit": "Chef-driven neighborhood brasserie — oysters, steak frites, butter sauces; premium dairy, beef, seafood.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 8277021779
 },
 {
  "id": "cur-055",
  "name": "Black Forest Pastry Shop",
  "category": "Bakery",
  "cuisine": "German / European pastry",
  "street": "52 Lewis St, Greenwich, CT 06830",
  "town": "Greenwich",
  "state": "CT",
  "lat": 41.028885,
  "lng": -73.624658,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 629-9330",
  "contact": "blackforestpastryshop.com",
  "segment": "Bakery-patisserie",
  "whyFit": "Bäckermeister-run konditorei, all-scratch since 1982 — steady premium butter, chocolate, flour volume.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-056",
  "name": "Sweet Lisa's Exquisite Cakes",
  "category": "Bakery",
  "cuisine": "Custom / wedding cakes",
  "street": "3 Field Rd, Cos Cob, CT 06807",
  "town": "Cos Cob",
  "state": "CT",
  "lat": 41.058115,
  "lng": -73.58266,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 869-9545",
  "contact": "Owners Lisa & Stephen Maronian · info@sweetlisas.com",
  "segment": "Bakery-patisserie",
  "whyFit": "Premier Greenwich wedding-cake studio, premium-only ingredients — couverture, high-fat butter, specialty flour.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-057",
  "name": "Columbus Park Trattoria",
  "category": "Restaurant",
  "cuisine": "Italian, house-made pasta",
  "street": "205 Main St, Stamford, CT 06901",
  "town": "Stamford",
  "state": "CT",
  "lat": 41.052953,
  "lng": -73.541855,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 967-9191",
  "contact": "Marchetti family · columbusparktrattoria.com",
  "segment": "Fine dining",
  "whyFit": "Family chef-owned institution since 1987, hand-rolled pastas; family group runs two more Fairfield County restaurants.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-058",
  "name": "Ten Twenty Post Oyster Bar & Bistro",
  "category": "Restaurant",
  "cuisine": "French bistro / seafood",
  "street": "1020 Post Rd, Darien, CT 06820",
  "town": "Darien",
  "state": "CT",
  "lat": 41.07554,
  "lng": -73.471815,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 655-1020",
  "contact": "tentwentypost.com (Pearl Restaurant Group)",
  "segment": "Upscale casual",
  "whyFit": "Pearl Restaurant Group (with Elm Street Oyster House, Greenwich + Ruby's, Rye) — seafood-centric multi-unit group spanning both states.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-059",
  "name": "Flour Water Salt Bread",
  "category": "Bakery",
  "cuisine": "Artisan sourdough",
  "street": "20 Grove St, Darien, CT 06820",
  "town": "Darien",
  "state": "CT",
  "lat": 41.075689,
  "lng": -73.472963,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 202-7776",
  "contact": "flourwatersaltbread.com",
  "segment": "Bakery-patisserie",
  "whyFit": "Cult-following naturally-leavened bakery — specialty flour and premium butter are its core inputs.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-060",
  "name": "The Spread",
  "category": "Restaurant",
  "cuisine": "New American",
  "street": "127 Washington St, South Norwalk, CT 06854",
  "town": "Norwalk (SoNo)",
  "state": "CT",
  "lat": 41.099047,
  "lng": -73.417887,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 939-1111",
  "contact": "Owners Cortes/Hickey/Rasile/Longyear · thespreadsono.com",
  "segment": "Upscale casual",
  "whyFit": "Chef-driven scratch kitchen; same group runs El Segundo + Magic 5 Pie Co. — multi-unit with catering.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-061",
  "name": "Wave Hill Breads",
  "category": "Bakery",
  "cuisine": "Artisan bread",
  "street": "239 Westport Ave, Norwalk, CT 06851",
  "town": "Norwalk",
  "state": "CT",
  "lat": 41.124505,
  "lng": -73.397389,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 423-0575",
  "contact": "wave-hill-breads.square.site",
  "segment": "Bakery (wholesale)",
  "whyFit": "Long-established wholesale artisan bread bakery supplying restaurants regionwide — bulk flour volume.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-062",
  "name": "Kawa Ni",
  "category": "Restaurant",
  "cuisine": "Japanese izakaya",
  "street": "19A Bridge Square, Westport, CT 06880",
  "town": "Westport",
  "state": "CT",
  "lat": 41.122301,
  "lng": -73.370221,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 987-3205",
  "contact": "Chef-owner Bill Taibe · sarah@kawaniwestport.com",
  "segment": "Upscale casual",
  "whyFit": "Seasonal chef-driven izakaya from one of CT's best-known chefs — rotating premium product.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-063",
  "name": "Le Rouge Chocolates by Aarti",
  "category": "Bakery",
  "cuisine": "Handmade chocolates",
  "street": "190 Main St, Westport, CT 06880",
  "town": "Westport",
  "state": "CT",
  "lat": 41.144087,
  "lng": -73.361674,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 293-6106",
  "contact": "Chocolatier Aarti Khosla · lerouge.aarti@gmail.com",
  "segment": "Chocolatier",
  "whyFit": "Artisan bonbons and cakes made on-site — direct couverture chocolate, butter, cream buyer.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-064",
  "name": "Luc's Café & Restaurant",
  "category": "Restaurant",
  "cuisine": "French bistro",
  "street": "3 Big Shop Ln, Ridgefield, CT 06877",
  "town": "Ridgefield",
  "state": "CT",
  "lat": 41.282565,
  "lng": -73.497246,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 894-8522",
  "contact": "lucscafe.com",
  "segment": "Upscale casual",
  "whyFit": "Authentic French bistro since 2001, all-day service — daily butter, cream, French staples.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-065",
  "name": "À Table with Sarah & Bernard",
  "category": "Caterer",
  "cuisine": "French",
  "street": "109 Danbury Rd (Copps Hill Marketplace), Ridgefield, CT 06877",
  "town": "Ridgefield",
  "state": "CT",
  "lat": 41.292762,
  "lng": -73.493292,
  "approxLoc": null,
  "fitScore": 85,
  "myRating": 4,
  "phone": "(203) 438-8282",
  "contact": "Sarah & Bernard Bouissou (ex-Le Cirque) · admin@atableus.com",
  "segment": "Caterer / gourmet market",
  "whyFit": "The former Bernard's fine-dining team — fine-dining-grade ingredient buyers with catering volume and a pastry counter.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-066",
  "name": "La Lanterna Restaurant & Caffe",
  "category": "Restaurant",
  "cuisine": "Tuscan Italian",
  "street": "23 Gray Oaks Ave, Yonkers, NY 10710",
  "town": "Yonkers",
  "state": "NY",
  "lat": 40.975881,
  "lng": -73.867978,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 476-3060",
  "contact": "Facebook: La.Lanterna.Restaurant",
  "segment": "Upscale casual",
  "whyFit": "Long-running independent with wine garden; scratch Italian kitchen — oil, flour, cheese.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 6556171865
 },
 {
  "id": "cur-067",
  "name": "Alvin & Friends",
  "category": "Restaurant",
  "cuisine": "Southern / Caribbean",
  "street": "14 Memorial Hwy, New Rochelle, NY 10801",
  "town": "New Rochelle",
  "state": "NY",
  "lat": 40.909002,
  "lng": -73.782448,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 654-6549",
  "contact": "Owner Alvin Clayton · alvinandfriendsrestaurant.com",
  "segment": "Upscale casual",
  "whyFit": "Owner-driven institution with scratch kitchen + active private-event trade.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 1419742050
 },
 {
  "id": "cur-068",
  "name": "Rosie's Bistro Italiano",
  "category": "Restaurant",
  "cuisine": "Italian",
  "street": "10 Palmer Ave, Bronxville, NY 10708",
  "town": "Bronxville",
  "state": "NY",
  "lat": 40.941342,
  "lng": -73.837889,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 793-2000",
  "contact": "On OpenTable",
  "segment": "Upscale casual",
  "whyFit": "Busy village Italian; fresh pasta and veal — reliable flour/oil/dairy in a wealthy trade area.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 12222666168
 },
 {
  "id": "cur-069",
  "name": "Scalini Osteria",
  "category": "Restaurant",
  "cuisine": "Italian osteria",
  "street": "65 Pondfield Rd, Bronxville, NY 10708",
  "town": "Bronxville",
  "state": "NY",
  "lat": 40.940625,
  "lng": -73.833445,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 337-4935",
  "contact": "scaliniosteria.com",
  "segment": "Upscale casual",
  "whyFit": "Scratch pasta menu one street from Rosie's — two stops, one visit (route density).",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 12092405959
 },
 {
  "id": "cur-070",
  "name": "Polpettina",
  "category": "Restaurant",
  "cuisine": "Farm-to-table Italian",
  "street": "102 Fisher Ave, Eastchester, NY 10709",
  "town": "Eastchester",
  "state": "NY",
  "lat": 40.95683,
  "lng": -73.81651,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 961-0061",
  "contact": "polpettina.com",
  "segment": "Quality fast-casual",
  "whyFit": "Self-described locally-sourced, high-quality kitchen — receptive to specialty upsell.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-071",
  "name": "Standing Room Only Fine Foods",
  "category": "Caterer",
  "cuisine": "Upscale American catering",
  "street": "1491 Weaver St, Scarsdale, NY 10583",
  "town": "Scarsdale",
  "state": "NY",
  "lat": 40.978423,
  "lng": -73.775851,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 472-3002",
  "contact": "srofinefoods.com",
  "segment": "Caterer",
  "whyFit": "Established full-service caterer — candidate for broadline-to-specialty conversion on proteins/dairy.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-072",
  "name": "Sonora",
  "category": "Restaurant",
  "cuisine": "Nuevo Latino",
  "street": "179 Rectory St, Port Chester, NY 10573",
  "town": "Port Chester",
  "state": "NY",
  "lat": 41.009042,
  "lng": -73.660532,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 933-0200",
  "contact": "Chef-owner Rafael Palomino · sonorarestaurantgroup@gmail.com",
  "segment": "Upscale casual",
  "whyFit": "Cookbook-author chef-owner, multi-state presence; scratch Latin kitchen with wild seafood.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-073",
  "name": "Hajime Japanese Restaurant",
  "category": "Restaurant",
  "cuisine": "Japanese / sushi",
  "street": "267 Halstead Ave, Harrison, NY 10528",
  "town": "Harrison",
  "state": "NY",
  "lat": 40.968651,
  "lng": -73.713177,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 777-1543",
  "contact": "Phone reservations only",
  "segment": "Upscale casual",
  "whyFit": "Serious chef-run sushi house — premium seafood buyer, though may lean on Japanese specialty importers.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-074",
  "name": "Trattoria 632",
  "category": "Restaurant",
  "cuisine": "Italian, wood-fired",
  "street": "632 Anderson Hill Rd, Purchase, NY 10577",
  "town": "Purchase",
  "state": "NY",
  "lat": 41.03795,
  "lng": -73.702547,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 481-5811",
  "contact": "trattoria632.com",
  "segment": "Upscale casual",
  "whyFit": "Scratch Italian serving the Purchase corporate corridor — strong lunch + catering trade.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-075",
  "name": "Granita Cucina & Bar",
  "category": "Restaurant",
  "cuisine": "Contemporary Italian",
  "street": "202 E Hartsdale Ave, Hartsdale, NY 10530",
  "town": "Hartsdale",
  "state": "NY",
  "lat": 41.012862,
  "lng": -73.796374,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 725-8420",
  "contact": "granita202@gmail.com · granitany.com",
  "segment": "Upscale casual",
  "whyFit": "Chef-driven: handcrafted pastas, wood-fired oven — best premium fit on the E. Hartsdale strip.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-076",
  "name": "Chutney Masala",
  "category": "Restaurant",
  "cuisine": "Modern Indian",
  "street": "76 Main St, Irvington, NY 10533",
  "town": "Irvington",
  "state": "NY",
  "lat": 41.039201,
  "lng": -73.868459,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 591-5500",
  "contact": "Chef-owner Navjot Arora · anu@chutneymasalabistro.com",
  "segment": "Upscale casual",
  "whyFit": "Michelin-recognized 2022-25; menu touts provenance (free-range lamb, wild seafood) — pays for quality.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-077",
  "name": "Geordane's Neighborhood Market",
  "category": "Caterer",
  "cuisine": "Prepared foods / catering",
  "street": "57 Main St, Irvington, NY 10533",
  "town": "Irvington",
  "state": "NY",
  "lat": 41.039463,
  "lng": -73.869615,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 591-6911",
  "contact": "geordanes.com",
  "segment": "Caterer / market",
  "whyFit": "Gourmet market + active event catering — specialty pantry, cheese, protein beyond restaurant channels.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-078",
  "name": "Sweet Grass Grill",
  "category": "Restaurant",
  "cuisine": "Farm-to-table American",
  "street": "24 Main St, Tarrytown, NY 10591",
  "town": "Tarrytown",
  "state": "NY",
  "lat": 41.076713,
  "lng": -73.860677,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 631-0000",
  "contact": "sweetgrassgrill.com (ERL Hospitality)",
  "segment": "Upscale casual",
  "whyFit": "Weekly-changing menu built on farm relationships — quality buyers by philosophy.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 6097092766
 },
 {
  "id": "cur-079",
  "name": "Southern Table Kitchen & Bar",
  "category": "Restaurant",
  "cuisine": "Southern American",
  "street": "39 Marble Ave, Pleasantville, NY 10570",
  "town": "Pleasantville",
  "state": "NY",
  "lat": 41.132246,
  "lng": -73.791852,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 618-3355",
  "contact": "southern-table.com",
  "segment": "Upscale casual",
  "whyFit": "Michelin Guide-listed scratch Southern kitchen — heavy butter/flour usage profile.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-080",
  "name": "The Whitlock",
  "category": "Restaurant",
  "cuisine": "Farm-to-table bistro",
  "street": "17 Katonah Ave, Katonah, NY 10536",
  "town": "Katonah",
  "state": "NY",
  "lat": 41.247218,
  "lng": -73.660814,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 232-8030",
  "contact": "thewhitlockkatonah.com",
  "segment": "Upscale casual",
  "whyFit": "Chef-driven bistro anchoring Katonah's strip — good mid-size protein and dairy account.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-081",
  "name": "Le Fontane Ristorante",
  "category": "Restaurant",
  "cuisine": "Classic Italian",
  "street": "137 Route 100, Katonah, NY 10536",
  "town": "Katonah",
  "state": "NY",
  "lat": 41.283167,
  "lng": -73.708888,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 232-9619",
  "contact": "lefontanerestaurant.com",
  "segment": "Upscale casual",
  "whyFit": "Long-standing white-tablecloth Italian with banquet space — oil, veal, imported Italian goods.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 13063574949
 },
 {
  "id": "cur-082",
  "name": "Homestyle Desserts Bakery",
  "category": "Bakery",
  "cuisine": "Retail / wedding cakes",
  "street": "24 S Water St, Peekskill, NY 10566",
  "town": "Peekskill",
  "state": "NY",
  "lat": 41.287792,
  "lng": -73.929048,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(914) 737-4659",
  "contact": "facebook.com/HomeStyleDessertsBakery",
  "segment": "Bakery",
  "whyFit": "Decades-old high-volume bakery with big custom-cake business — bulk butter, chocolate, flour.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-083",
  "name": "MIKU Sushi Bar & Restaurant",
  "category": "Restaurant",
  "cuisine": "Japanese / sushi",
  "street": "68 Greenwich Ave, Greenwich, CT 06830",
  "town": "Greenwich",
  "state": "CT",
  "lat": 41.029758,
  "lng": -73.626627,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 900-7676",
  "contact": "FB @mikugreenwich",
  "segment": "Upscale casual",
  "whyFit": "Independent premium sushi on the Avenue — quality-fish buyer, though sushi houses often use Japanese importers.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-084",
  "name": "Méli-Mélo Crêperie & Catering",
  "category": "Caterer",
  "cuisine": "French crêperie",
  "street": "362 Greenwich Ave, Greenwich, CT 06830",
  "town": "Greenwich",
  "state": "CT",
  "lat": 41.02472,
  "lng": -73.625623,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 629-6153",
  "contact": "Chef-owner Marc Penvenne · melimelogreenwich.com",
  "segment": "Fast-casual + caterer",
  "whyFit": "30-yr scratch crêperie — butter/flour volume plus an active catering arm.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 13740911928
 },
 {
  "id": "cur-085",
  "name": "Bar Rosso",
  "category": "Restaurant",
  "cuisine": "Italian / wine bar",
  "street": "28 Spring St, Stamford, CT 06901",
  "town": "Stamford",
  "state": "CT",
  "lat": 41.056976,
  "lng": -73.53973,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 388-8640",
  "contact": "barrosso.com",
  "segment": "Upscale casual",
  "whyFit": "Wood-fired oven, house pastas, salumi/cheese program — olive oil, imported cheese, flour.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 8014921024
 },
 {
  "id": "cur-086",
  "name": "Cava Wine Bar & Wood Grille",
  "category": "Restaurant",
  "cuisine": "Italian / wood grill",
  "street": "2 Forest St, New Canaan, CT 06840",
  "town": "New Canaan",
  "state": "CT",
  "lat": 41.147749,
  "lng": -73.492195,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 966-6946",
  "contact": "info@cavawinebarct.com · cavawinebarct.com",
  "segment": "Upscale casual",
  "whyFit": "Independent downtown Italian — olive oil, imported goods, premium beef.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-087",
  "name": "Valencia Cocina",
  "category": "Restaurant",
  "cuisine": "Venezuelan / Latin",
  "street": "164 Main St, Norwalk, CT 06851",
  "town": "Norwalk",
  "state": "CT",
  "lat": 41.12554,
  "lng": -73.418877,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 846-8009",
  "contact": "Chef-owner Michael Young · valencialuncheria.com",
  "segment": "Quality fast-casual",
  "whyFit": "Cult-favorite chef-driven kitchen, relaunched early 2026 with wood-fire menu; Young co-owns Bodega Taco Bar (2 units).",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-088",
  "name": "Bianco Rosso Wine Bar & Restaurant",
  "category": "Restaurant",
  "cuisine": "Contemporary Italian",
  "street": "151 Old Ridgefield Rd, Wilton, CT 06897",
  "town": "Wilton",
  "state": "CT",
  "lat": 41.192177,
  "lng": -73.4308,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 529-3800",
  "contact": "biancorossorestaurantandbar.com",
  "segment": "Upscale casual",
  "whyFit": "House-made pastas + serious wine program — EVOO, flour, imported cheese.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-089",
  "name": "Aranci 67",
  "category": "Restaurant",
  "cuisine": "Sicilian Italian",
  "street": "142 Old Ridgefield Rd, Wilton, CT 06897",
  "town": "Wilton",
  "state": "CT",
  "lat": 41.192808,
  "lng": -73.430921,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 587-1300",
  "contact": "aranci67.com",
  "segment": "Upscale casual",
  "whyFit": "Intimate chef-owned trattoria, dinner-only — scratch kitchen, premium seafood and Italian imports.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-090",
  "name": "Ross Artisanal Bakery & Café",
  "category": "Bakery",
  "cuisine": "Artisan bread / café",
  "street": "109 Danbury Rd, Ridgefield, CT 06877",
  "town": "Ridgefield",
  "state": "CT",
  "lat": 41.292762,
  "lng": -73.493292,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 438-4822",
  "contact": "info@rossbread.com",
  "segment": "Bakery-patisserie",
  "whyFit": "Scratch bread and pastry with holiday catering menus — consistent flour/butter volume.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 12133854972
 },
 {
  "id": "cur-091",
  "name": "Gallo Ristorante",
  "category": "Restaurant",
  "cuisine": "Italian",
  "street": "5 Grove St, Ridgefield, CT 06877",
  "town": "Ridgefield",
  "state": "CT",
  "lat": 41.284042,
  "lng": -73.494969,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 431-7726",
  "contact": "galloridgefield.com",
  "segment": "Upscale casual",
  "whyFit": "Family-owned, wood-fired pizza + homemade pastas; site emphasizes ingredient sourcing — oil, 00 flour, imports.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-092",
  "name": "Old Post Tavern",
  "category": "Restaurant",
  "cuisine": "New American / seafood",
  "street": "1418 Post Rd, Fairfield, CT 06824",
  "town": "Fairfield",
  "state": "CT",
  "lat": 41.141487,
  "lng": -73.256511,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 292-8631",
  "contact": "angel@oldposttavern.com · oldposttavern.com",
  "segment": "Upscale casual",
  "whyFit": "Independent scratch-kitchen tavern, seafood-forward + private events — prime beef and seafood potential.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-093",
  "name": "Bodega Taco Bar",
  "category": "Restaurant",
  "cuisine": "Modern Mexican",
  "street": "1700 Post Rd, Fairfield, CT 06824",
  "town": "Fairfield",
  "state": "CT",
  "lat": 41.14109,
  "lng": -73.261009,
  "approxLoc": null,
  "fitScore": 70,
  "myRating": 3,
  "phone": "(203) 292-9590",
  "contact": "Co-owner Chef Michael Young · bodegatacobar.com",
  "segment": "Quality fast-casual",
  "whyFit": "Chef-driven modern Mexican, two locations (Fairfield + Darien) — cross-sell with Valencia Cocina, Norwalk.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 },
 {
  "id": "cur-094",
  "name": "Red Plum",
  "category": "Restaurant",
  "cuisine": "Asian fusion / sushi",
  "street": "251 Mamaroneck Ave, Mamaroneck, NY 10543",
  "town": "Mamaroneck",
  "state": "NY",
  "lat": 40.950538,
  "lng": -73.733931,
  "approxLoc": null,
  "fitScore": 55,
  "myRating": 2,
  "phone": "(914) 777-6888",
  "contact": "On OpenTable · Facebook: Red Plum Restaurant",
  "segment": "Upscale casual",
  "whyFit": "Sashimi-grade seafood buyer; fusion menu open to crossover items — but limited specialty breadth.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 7851477759
 },
 {
  "id": "cur-095",
  "name": "The Tavern at Croton Landing",
  "category": "Restaurant",
  "cuisine": "American tavern",
  "street": "41 N Riverside Ave, Croton-on-Hudson, NY 10520",
  "town": "Croton-on-Hudson",
  "state": "NY",
  "lat": 41.207118,
  "lng": -73.893177,
  "approxLoc": null,
  "fitScore": 55,
  "myRating": 2,
  "phone": "(914) 271-8020",
  "contact": "thetavernatthecrotonlanding@gmail.com",
  "segment": "Casual tavern",
  "whyFit": "Moderate fit, but best entry point in a town whose top seafood spot (Ocean House) just closed — demand gap.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": 6589796231
 },
 {
  "id": "cur-096",
  "name": "Travelers Rest",
  "category": "Caterer",
  "cuisine": "Continental American",
  "street": "25 Route 100, Ossining, NY 10562",
  "town": "Ossining",
  "state": "NY",
  "lat": 41.1628,
  "lng": -73.8615,
  "approxLoc": true,
  "fitScore": 55,
  "myRating": 2,
  "phone": "(914) 941-7744",
  "contact": "Nelson family",
  "segment": "Caterer / banquets",
  "whyFit": "Wedding/banquet volume = steady bulk buyer, but traditional menu, less specialty-driven.",
  "monthlyValue": 0,
  "status": "new",
  "opening": null,
  "curated": true,
  "osmId": null
 }
];
